print ("Anna Marie Tenorio")
print ("Pili, Mogpog Marinduque")
print ("December 30, 2001")
print ("Marinduque State College")
print ("Bachelor of Science in Information Technology")
print ("Second Year")
print ("Reading")
print ("Coding")
print ("Watching dramas")
print ("Cooking")
print ("Learning a new Programming Language")